services:
  backend:
    build: ../healthcare_API-fukashin #基準の位置を設定今回はhealthcare_API-fukashinフォルダのDockerファイルを実行している
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - ../healthcare_API-fukashin:/app #../healthcare_API-fukashinファイルをコンテナの/appにマウントする　
    environment:
      - DEBUG=1
      - DATABASE_HOST=db
      - DATABASE_NAME=healthcare_db
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_PORT=5432